baseurl = "https://serohub.netlify.app/"
title = "Serohub"
author = "Hermholtz HZI"
copyright = "Copyright (c) 2020 Hermholtz HZI"
canonifyurls = true
paginate = 3
theme="hugo-finite"

[params]
logo = "img/hzi_logo_white.png"
# Date format (refer to Go's date format: http://flippinggodateformat.com)
# Examples: "Mon, Jan 2, 2006" or "2006-01-02"
#date_format = "2 January 2006"

# Publications can have a Params.publication for citation references.
# Publications can have a Params.kind, such as "book".
# Both parameters are mapped to an icon in partials/pub-icon.html.

bio_full = "Overview of all COVID19 Seroprevalance studies performed in Germany"
twitter_feed = "serohub"

# Number of posts to show on main page.
default_count = 3

sharing = true
leaflet_enable = true
leaflet_source = "data/researchers.csv"
mapbox_token = "pk.eyJ1Ijoic3RlcGhsb2NrZSIsImEiOiJjazlzOWg4Nm4wMnloM2Ztb3ZqcDl1bnZiIn0.TbIjIGJN69vEyaINwJTclA"
leaflet_central_lat = 52.5200
leaflet_central_long = 13.4050

[markup]
  [markup.highlight]
    style = "manni"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# [[params.education]]
#   course = "Bachelor in Civil Law"
#   institution = "University of Orléans"
#   year = 1626

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:serohub@helmholtz-hzi.de"
  text = "serohub@helmholtz-hzi.de"
    
[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/serohub"
  text = "@serohub"
  site = "Twitter"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "https://github.com/hzi-braunschweig/serohub"
  text = "hzi-braunschweig/serohub"
  site = "GitHub"

# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Publications"
  url = "/publication/"
  weight = 2

[[menu.main]]
  name = "Studies"
  url = "/studies/"
  weight = 1

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.JSON]
mediaType = "application/json"
baseName = "studies"
isPlainText =  true
