baseurl = "https://serohub.netlify.app/"
title = "Serohub"
author = "Hermholtz HZI"
copyright = "Copyright (c) 2020 Hermholtz HZI"
canonifyurls = true
paginate = 3
theme="hugo-finite"

[params]
logo = "img/logo-hzi2-en.svg"
# Date format (refer to Go's date format: http://flippinggodateformat.com)
# Examples: "Mon, Jan 2, 2006" or "2006-01-02"
#date_format = "2 January 2006"

# Publications can have a Params.publication for citation references.
# Publications can have a Params.kind, such as "book".
# Both parameters are mapped to an icon in partials/pub-icon.html.

bio_full = "Overview of all COVID19 Seroprevalance studies performed in Germany"
twitter_feed = "helmholtz_hzi"

# Title of posts section on main page.
posts_title = "Studies"

# Number of posts to show on main page.
posts_count = 2

# Title of publications section on main page.
pubs_title = "Publications"

# Number of publications to show on main page.
pubs_count = 2

mainSections = ["study", "publications"]


leaflet_enable = true
leaflet_source = "data/researchers.csv"
mapbox_token = "pk.eyJ1Ijoic3RlcGhsb2NrZSIsImEiOiJjazlzOWg4Nm4wMnloM2Ztb3ZqcDl1bnZiIn0.TbIjIGJN69vEyaINwJTclA"
leaflet_central_lat = 52.5200
leaflet_central_long = 13.4050

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# [[params.education]]
#   course = "Bachelor in Civil Law"
#   institution = "University of Orléans"
#   year = 1626

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:Stephan.Gloeckner@helmholtz-hzi.de"
  text = "Stephan Glöckner"
    
[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/Helmholtz_HZI"
  text = "@Helmholtz_HZI"
  site = "Twitter"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "https://github.com/nightingalehq/serohub"
  text = "nightingalehq/serohub"
  site = "GitHub"

[[params.social]]
  icon = "researchgate"
  icon_pack = "ai"
  link = "https://www.researchgate.net/profile/Pierre_Fermat3"
  text = "ResearchGate"



# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Publications"
  url = "/publication/"
  weight = 2

[[menu.main]]
  name = "Studies"
  url = "/studies/"
  weight = 1

